import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { Kysely } from 'kysely';
import { generate, PostgresDialect } from 'kysely-codegen';
import { migrate, startPostgres } from '../verify/postgres.ts';

const target = 'shared/db/types.ts';
const path = fileURLToPath(new URL(`../../${target}`, import.meta.url));
const write = process.argv.includes('--write');

const postgres = await startPostgres();
try {
  const url = postgres.url('types');
  migrate(url);
  const dialect = new PostgresDialect();
  const db = new Kysely<unknown>({ dialect: await dialect.createKyselyDialect({ connectionString: url }) });
  try {
    const fresh = await generate({ db, dialect, skipAutogeneratedFileComment: true, excludePattern: 'schema_migrations', outFile: null });
    if (write) writeFileSync(path, fresh);
    else if (!existsSync(path) || readFileSync(path, 'utf8') !== fresh) {
      process.stdout.write(`${target} differs from a fresh generation. Run npm run db:types.\n`);
      process.exitCode = 1;
    }
  } finally {
    await db.destroy();
  }
} finally {
  await postgres.stop();
}
